quote="Honesty is the first chapter in the book of wisdom."
dlugosc=len(quote)
print("1",dlugosc)
print('2',quote[-7:-1])
print('3',quote[:len(quote)//2])
print('4',quote[-1])
print('5',quote[len(quote)//2::3])
print('6',quote[: :2])
print('7',quote[: :-1])
print('8',quote.replace('wisdom', 'friendship'))